---
- name: HDFS configuration (create users dir)
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /users/"

- name: HDFS configuration (create log dir)
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /log/"

- name: HDFS configuration (create history dir)
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /log/history"

- name: HDFS configuration (set log folder rights)
  command: "{{ hadoop_home }}/bin/hdfs dfs -chmod go+w /log"

- name: HDFS configuration (set history folder rights)
  command: "{{ hadoop_home }}/bin/hdfs dfs -chmod go+w /log/history"

#- name: Copy hadoop environment script
#  copy:
#    dest: /etc/profile.d/hadoop.sh
#    src: hadoop.sh
#    mode: 0644

- name: Copy hadoop environment script
  template:
    src: "hadoop.sh"
    dest: "/etc/profile.d/hadoop.sh"
    mode: 0644
    force: yes

- name: create HDFS homes
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /users/{{ item.value.name }}"
  with_dict: "{{ users_dict }}"

- name: create HDFS homes
  command: "{{ hadoop_home }}/bin/hdfs dfs -chown {{ item.value.name }}:{{ item.value.name }} /users/{{ item.value.name }}"
  with_dict: "{{ users_dict }}"