---
# RedHat related OSs
- name: Yum install {{ packages }}
  yum: pkg={{ packages }} state=present
  when: "ansible_os_family == 'RedHat'"
  vars:
    packages:
    - wget
    - tar
    - gzip
    - unzip
#    - java-1.8.0-openjdk
  tags:
    - install

- name: Ubuntu 14 install software-properties-common
  apt: name=software-properties-common
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
  tags:
    - install

- name: Ubuntu 14 install OpenJDK PPA repo
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
  tags:
    - install

# Debian related OSs
- name: Apt install {{ packages }}
  apt: pkg={{ packages }} state=present update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  vars:
    packages:
    - wget
    - tar
    - gzip
    - unzip
#    - openjdk-8-jre

  tags:
    - install

- set_fact: hadoop_file="{{ lookup('url', 'http://www-eu.apache.org/dist/hadoop/common/stable2/', split_lines=False) | regex_search('(hadoop-)(\d\.\d\.\d)(\.tar\.gz)') }}"
  when: hadoop_version == 'latest'
  tags:
    - install

- set_fact: hadoop_version="{{ hadoop_file | regex_search('(\d\.\d\.\d)') }}"
  when: hadoop_version == 'latest'
  tags:
    - install

- name: "Download {{ hadoop_version }}"
  get_url: url={{ hadoop_mirrors|random }}/hadoop-{{ hadoop_version }}.tar.gz dest={{ hadoop_home }}-{{ hadoop_version }}.tar.gz force=no
  register: result
  until: result is success
  retries: 5
  delay: 2
  tags:
    - install

- name: Unarchive hadoop tgz
  unarchive: src={{ hadoop_home }}-{{ hadoop_version }}.tar.gz dest={{ hadoop_home.split("/")[0:-1]|join("/") }} creates={{ hadoop_home }}-{{ hadoop_version }} copy=no
  tags:
    - install

- name: "Create {{ hadoop_home }} dir"
  file: dest={{ hadoop_home }} src={{ hadoop_home }}-{{ hadoop_version }} state=link

- name: Set JAVA_HOME in hadoop-env.sh in RH
  lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME=/usr/lib/jvm/jre-1.8.0"
  when: "ansible_os_family == 'RedHat'"

- name: Set JAVA_HOME in hadoop-env.sh Deb
  lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
  when: "ansible_os_family == 'Debian'"
