---
# Add a fast check to speed reconfiguration
- stat: path={{ hadoop_home }}
  register: hadoop_installed

- include: users.yml

- include: ssh_keys.yml

- include: install.yml
  when: not hadoop_installed.stat.exists

- include: configure.yml

- include: configure_users.yml
  when: users_dict.values()
