---
- name: "Add Groups"
  group: name={{ item }}
         state=present
  with_items:
  - "{{ hadoop_system_group }}"
  tags:
    - users

- name: "Add user"
  user: name={{ item }}
        group={{ item }}
        createhome=yes
        state=present
  with_items:
  - "{{ hadoop_system_user }}"
  tags:
    - users